baseURL = "https://omark.dev/"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true
# pagination = 10

title = "omarkdev"
author = "Marcos Felipe"
copyright = "[Home](/) &#183;"

theme = "simpleness"
googleAnalytics = ""

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2019"
  showmonth = true
  slogan = ""
  description = "Personal blog"
  disqus = ""

[params.valine]
  enable = false
  lang = 'en' # zh-CN
  appId = ''
  appKey = ''
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  avatar = 'robohash'
  visitor = true
  enableHeaderVisitor = true
  debug = true

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "Sobre"
  url = "/about/"
  weight = 2

[social]
  github = "https://github.com/omarkdev"
  twitter = "https://twitter.com/@omarkdev"
  instagram = "https://instagram.com/mmmarcosfelipe"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4